name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install CML and dependencies
        run: |
          pip install -r requirements.txt
          pip install cml

      - name: Run ML workflow
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "MODEL METRICS" > report.md
          cat metrics.txt >> report.md

          cml-publish feature_importance.png --md >> report.md
          cml-publish residuals.png --md >> report.md

          cml-send-comment report.md
